name: Java CI with Maven

on:
  push:
    branches: [ main, test]
  pull_request:
    branches: [ main, test]

jobs:
  build-and-test:
    name: JDK ${{matrix.java-version}} JVM build and tests
    timeout-minutes: 110
    strategy:
      fail-fast: false
      matrix:
        java-version: [11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: actions/setup-java@v1
      name: Set up JDK ${{ matrix.java-version }}
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}

    - name: Build with Maven
      run: mvn clean install
    
    - name: Upload build reports (if build failed)
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/ # or path/to/artifact

      
  
